#!/usr/bin/env ruby

require 'rubygems'
require 'commander'
require_relative '../lib/generator'
require_relative './build'

class MyApplication
  include Commander::Methods
  # include whatever modules you need
  include Build

  def run
    program :name, 'm2b'
    program :version, '0.0.1'
    program :description, 'Markdown to blog'
    default_command  :build

    command :build do |c|
      self.execute(c)
    end
    
    run!
  end
end

MyApplication.new.run

# MyApplication.new.run if $0 == __FILE__
