#!/usr/bin/env ruby

require 'rubygems'
require 'commander'
require_relative '../lib/generator'
require_relative './build'
require_relative './mailer'

class MyApplication
  include Commander::Methods
  # include whatever modules you need
  include BuildCommand
  include MailCommand

  def run
    program :name, 'm2m'
    program :version, '0.0.1'
    program :description, 'Markdown to More'
    default_command  :build

    command :build do |c|
      self.build(c)
    end

    command :mail do |c|
      self.mail(c)
    end
    
    run!
  end
end

MyApplication.new.run

# MyApplication.new.run if $0 == __FILE__
