#!/usr/bin/env ruby

require 'rubygems'
require 'commander'
require_relative '../lib/generator'
require_relative './site'
require_relative './mailer'
require_relative './setup'
require_relative './server'

class Application
  include Commander::Methods
  # include whatever modules you need
  include SiteCommand
  include MailCommand
  include ServerCommand
  include SetupCommand

  def run
    program :name, 'm2m'
    program :version, '0.0.1'
    program :description, 'Markdown to More'
    default_command  :site

    #生成博客
    command :site do |c|
      self.site(c)
    end

    #启动服务器
    command :server do |c|
      self.server(c)
    end

    #发送邮件
    command :mail do |c|
      self.mail(c)
    end
    
    #配置相关
    command :setup do |c|
      self.setup c
    end

    run!
  end
end

Application.new.run

# MyApplication.new.run if $0 == __FILE__
